=== api-evangelist/amazon-snow-family/json-schema/amazon-snow-family-long-term-pricing-list-entry-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-snow-family/refs/heads/main/json-schema/amazon-snow-family-long-term-pricing-list-entry-schema.json",
  "title": "LongTermPricingListEntry",
  "description": "Each <code>LongTermPricingListEntry</code> object contains information about a long-term pricing type.",
  "type": "object",
  "properties": {
    "LongTermPricingId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LongTermPricingId"
        },
        {
          "description": "The ID of the long-term pricing type for the device."
        }
      ]
    },
    "LongTermPricingEndDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": "The end date the long-term pricing contract."
        }
      ]
    },
    "LongTermPricingStartDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": "The start date of the long-term pricing contract."
        }
      ]
    },
    "LongTermPricingType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LongTermPricingType"
        },
        {
          "description": "The type of long-term pricing that was selected for the device."
        }
      ]
    },
    "CurrentActiveJob": {
      "allOf": [
        {
          "$ref": "#/components/schemas/JobId"
        },
        {
          "description": "The current active jobs on the device the long-term pricing type."
        }
      ]
    },
    "ReplacementJob": {
      "allOf": [
        {
          "$ref": "#/components/schemas/JobId"
        },
        {
          "description": "A new device that replaces a device that is ordered with long-term pricing."
        }
      ]
    },
    "IsLongTermPricingAutoRenew": {
      "allOf": [
        {
          "$ref": "#/components/schemas/JavaBoolean"
        },
        {
          "description": "If set to <code>true</code>, specifies that the current long-term pricing type for the device should be automatically renewed before the long-term pricing contract expires."
        }
      ]
    },
    "LongTermPricingStatus": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The status of the long-term pricing type."
        }
      ]
    },
    "SnowballType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SnowballType"
        },
        {
          "description": "The type of Snow Family devices associated with this long-term pricing job."
        }
      ]
    },
    "JobIds": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LongTermPricingAssociatedJobIdList"
        },
        {
          "description": "The IDs of the jobs that are associated with a long-term pricing type."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-snow-family/examples/amazon-snow-family-long-term-pricing-list-entry-example.json
{
  "LongTermPricingId": "example-value",
  "LongTermPricingEndDate": "example-value",
  "LongTermPricingStartDate": "example-value",
  "LongTermPricingType": "example-value",
  "CurrentActiveJob": "example-value",
  "ReplacementJob": "example-value",
  "IsLongTermPricingAutoRenew": "example-value",
  "LongTermPricingStatus": "Active",
  "SnowballType": "example-value",
  "JobIds": "example-value"
}
