=== api-evangelist/amazon-snow-family/json-schema/amazon-snow-family-create-cluster-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-snow-family/refs/heads/main/json-schema/amazon-snow-family-create-cluster-request-schema.json",
  "title": "CreateClusterRequest",
  "description": "CreateClusterRequest schema from Amazon Snow Family API",
  "type": "object",
  "properties": {
    "JobType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/JobType"
        },
        {
          "description": "<p>The type of job for this cluster. Currently, the only job type supported for clusters is <code>LOCAL_USE</code>.</p> <p>For more information, see \"https://docs.aws.amazon.com/snowball/latest/snowcone-guide/snow-device-types.html\" (Snow Family Devices and Capacity) in the <i>Snowcone User Guide</i> or \"https://docs.aws.amazon.com/snowball/latest/developer-guide/snow-device-types.html\" (Snow Family Devices and Capacity) in the <i>Snowcone User Guide</i>.</p>"
        }
      ]
    },
    "Resources": {
      "allOf": [
        {
          "$ref": "#/components/schemas/JobResource"
        },
        {
          "description": "The resources associated with the cluster job. These resources include Amazon S3 buckets and optional Lambda functions written in the Python language. "
        }
      ]
    },
    "OnDeviceServiceConfiguration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OnDeviceServiceConfiguration"
        },
        {
          "description": "Specifies the service or services on the Snow Family device that your transferred data will be exported from or imported into. Amazon Web Services Snow Family device clusters support Amazon S3 and NFS (Network File System)."
        }
      ]
    },
    "Description": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "An optional description of this specific cluster, for example <code>Environmental Data Cluster-01</code>."
        }
      ]
    },
    "AddressId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AddressId"
        },
        {
          "description": "The ID for the address that you want the cluster shipped to."
        }
      ]
    },
    "KmsKeyARN": {
      "allOf": [
        {
          "$ref": "#/components/schemas/KmsKeyARN"
        },
        {
          "description": "The <code>KmsKeyARN</code> value that you want to associate with this cluster. <code>KmsKeyARN</code> values are created by using the <a href=\"https://docs.aws.amazon.com/kms/latest/APIReference/API_CreateKey.html\">CreateKey</a> API action in Key Management Service (KMS). "
        }
      ]
    },
    "RoleARN": {
      "allOf": [
        {
          "$ref": "#/components/schemas/RoleARN"
        },
        {
          "description": "The <code>RoleARN</code> that you want to associate with this cluster. <code>RoleArn</code> values are created by using the <a href=\"https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html\">CreateRole</a> API action in Identity and Access Management (IAM)."
        }
      ]
    },
    "SnowballType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SnowballType"
        },
        {
          "description": "<p>The type of Snow Family devices to use for this cluster. </p> <note> <p>For cluster jobs, Amazon Web Services Snow Family currently supports only the <code>EDGE</code> device type.</p> </note> <p>For more information, see \"https://docs.aws.amazon.com/snowball/latest/snowcone-guide/snow-device-types.html\" (Snow Family Devices and Capacity) in the <i>Snowcone User Guide</i> or \"https://docs.aws.amazon.com/snowball/latest/developer-guide/snow-device-types.html\" (Snow Family Devices and Capacity) in the <i>Snowcone User Guide</i>.</p>"
        }
      ]
    },
    "ShippingOption": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ShippingOption"
        },
        {
          "description": "<p>The shipping speed for each node in this cluster. This speed doesn't dictate how soon you'll get each Snowball Edge device, rather it represents how quickly each device moves to its destination while in transit. Regional shipping speeds are as follows: </p> <ul> <li> <p>In Australia, you have access to express shipping. Typically, Snow devices shipped express are delivered in about a day.</p> </li> <li> <p>In the European Union (EU), you have access to express shipping. Typically, Snow devices shipped express are delivered in about a day. In addition, most countries in the EU have access to standard shipping, which typically takes less than a week, one way.</p> </li> <li> <p>In India, Snow devices are delivered in one to seven days.</p> </li> <li> <p>In the United States of America (US), you have access to one-day shipping and two-day shipping.</p> </li> </ul> <ul> <li> <p>In Australia, you have access to express shipping. Typically, devices shipped express are delivered in about a day.</p> </li> <li> <p>In the European Union (EU), you have access to express shipping. Typically, Snow devices shipped express are delivered in about a day. In addition, most countries in the EU have access to standard shipping, which typically takes less than a week, one way.</p> </li> <li> <p>In India, Snow devices are delivered in one to seven days.</p> </li> <li> <p>In the US, you have access to one-day shipping and two-day shipping.</p> </li> </ul>"
        }
      ]
    },
    "Notification": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Notification"
        },
        {
          "description": "The Amazon Simple Notification Service (Amazon SNS) notification settings for this cluster."
        }
      ]
    },
    "ForwardingAddressId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AddressId"
        },
        {
          "description": "The forwarding address ID for a cluster. This field is not supported in most regions."
        }
      ]
    },
    "TaxDocuments": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TaxDocuments"
        },
        {
          "description": "The tax documents required in your Amazon Web Services Region."
        }
      ]
    },
    "RemoteManagement": {
      "allOf": [
        {
          "$ref": "#/components/schemas/RemoteManagement"
        },
        {
          "description": "Allows you to securely operate and manage Snow devices in a cluster remotely from outside of your internal network. When set to <code>INSTALLED_AUTOSTART</code>, remote management will automatically be available when the device arrives at your location. Otherwise, you need to use the Snowball Client to manage the device."
        }
      ]
    },
    "InitialClusterSize": {
      "allOf": [
        {
          "$ref": "#/components/schemas/InitialClusterSize"
        },
        {
          "description": "If provided, each job will be automatically created and associated with the new cluster. If not provided, will be treated as 0."
        }
      ]
    },
    "ForceCreateJobs": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "Force to create cluster when user attempts to overprovision or underprovision a cluster. A cluster is overprovisioned or underprovisioned if the initial size of the cluster is more (overprovisioned) or less (underprovisioned) than what needed to meet capacity requirement specified with <code>OnDeviceServiceConfiguration</code>."
        }
      ]
    },
    "LongTermPricingIds": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LongTermPricingIdList"
        },
        {
          "description": "Lists long-term pricing id that will be used to associate with jobs automatically created for the new cluster."
        }
      ]
    },
    "SnowballCapacityPreference": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SnowballCapacity"
        },
        {
          "description": "<p>If your job is being created in one of the US regions, you have the option of specifying what size Snow device you'd like for this job. In all other regions, Snowballs come with 80 TB in storage capacity.</p> <p>For more information, see \"https://docs.aws.amazon.com/snowball/latest/snowcone-guide/snow-device-types.html\" (Snow Family Devices and Capacity) in the <i>Snowcone User Guide</i> or \"https://docs.aws.amazon.com/snowball/latest/developer-guide/snow-device-types.html\" (Snow Family Devices and Capacity) in the <i>Snowcone User Guide</i>.</p>"
        }
      ]
    }
  },
  "required": [
    "JobType",
    "AddressId",
    "SnowballType",
    "ShippingOption"
  ]
}

=== api-evangelist/amazon-snow-family/examples/amazon-snow-family-create-cluster-request-example.json
{
  "JobType": "example-value",
  "Resources": "example-value",
  "OnDeviceServiceConfiguration": "example-value",
  "Description": "example-value",
  "AddressId": "example-value",
  "KmsKeyARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "RoleARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "SnowballType": "example-value",
  "ShippingOption": "example-value",
  "Notification": "example-value",
  "ForwardingAddressId": "example-value",
  "TaxDocuments": "example-value",
  "RemoteManagement": "example-value",
  "InitialClusterSize": "example-value",
  "ForceCreateJobs": "example-value",
  "LongTermPricingIds": "example-value",
  "SnowballCapacityPreference": "example-value"
}
