=== api-evangelist/amazon-snow-family/json-schema/amazon-snow-family-cluster-metadata-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-snow-family/refs/heads/main/json-schema/amazon-snow-family-cluster-metadata-schema.json",
  "title": "ClusterMetadata",
  "description": "Contains metadata about a specific cluster.",
  "type": "object",
  "properties": {
    "ClusterId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The automatically generated ID for a cluster."
        }
      ]
    },
    "Description": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The optional description of the cluster."
        }
      ]
    },
    "KmsKeyARN": {
      "allOf": [
        {
          "$ref": "#/components/schemas/KmsKeyARN"
        },
        {
          "description": "The <code>KmsKeyARN</code> Amazon Resource Name (ARN) associated with this cluster. This ARN was created using the <a href=\"https://docs.aws.amazon.com/kms/latest/APIReference/API_CreateKey.html\">CreateKey</a> API action in Key Management Service (KMS."
        }
      ]
    },
    "RoleARN": {
      "allOf": [
        {
          "$ref": "#/components/schemas/RoleARN"
        },
        {
          "description": "The role ARN associated with this cluster. This ARN was created using the <a href=\"https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html\">CreateRole</a> API action in Identity and Access Management (IAM)."
        }
      ]
    },
    "ClusterState": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ClusterState"
        },
        {
          "description": "The current status of the cluster."
        }
      ]
    },
    "JobType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/JobType"
        },
        {
          "description": "The type of job for this cluster. Currently, the only job type supported for clusters is <code>LOCAL_USE</code>."
        }
      ]
    },
    "SnowballType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SnowballType"
        },
        {
          "description": "<p>The type of Snowcone device to use for this cluster. </p> <note> <p>For cluster jobs, Amazon Web Services Snow Family currently supports only the <code>EDGE</code> device type.</p> </note>"
        }
      ]
    },
    "CreationDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": "The creation date for this cluster."
        }
      ]
    },
    "Resources": {
      "allOf": [
        {
          "$ref": "#/components/schemas/JobResource"
        },
        {
          "description": "The arrays of <a>JobResource</a> objects that can include updated <a>S3Resource</a> objects or <a>LambdaResource</a> objects."
        }
      ]
    },
    "AddressId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AddressId"
        },
        {
          "description": "The automatically generated ID for a specific address."
        }
      ]
    },
    "ShippingOption": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ShippingOption"
        },
        {
          "description": "<p>The shipping speed for each node in this cluster. This speed doesn't dictate how soon you'll get each device, rather it represents how quickly each device moves to its destination while in transit. Regional shipping speeds are as follows:</p> <ul> <li> <p>In Australia, you have access to express shipping. Typically, devices shipped express are delivered in about a day.</p> </li> <li> <p>In the European Union (EU), you have access to express shipping. Typically, Snow devices shipped express are delivered in about a day. In addition, most countries in the EU have access to standard shipping, which typically takes less than a week, one way.</p> </li> <li> <p>In India, Snow devices are delivered in one to seven days.</p> </li> <li> <p>In the US, you have access to one-day shipping and two-day shipping.</p> </li> </ul>"
        }
      ]
    },
    "Notification": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Notification"
        },
        {
          "description": "The Amazon Simple Notification Service (Amazon SNS) notification settings for this cluster."
        }
      ]
    },
    "ForwardingAddressId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AddressId"
        },
        {
          "description": "The ID of the address that you want a cluster shipped to, after it will be shipped to its primary address. This field is not supported in most regions."
        }
      ]
    },
    "TaxDocuments": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TaxDocuments"
        },
        {
          "description": "The tax documents required in your Amazon Web Services Region."
        }
      ]
    },
    "OnDeviceServiceConfiguration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OnDeviceServiceConfiguration"
        },
        {
          "description": "Represents metadata and configuration settings for services on an Amazon Web Services Snow Family device."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-snow-family/examples/amazon-snow-family-cluster-metadata-example.json
{
  "ClusterId": "example-value",
  "Description": "example-value",
  "KmsKeyARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "RoleARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "ClusterState": "example-value",
  "JobType": "example-value",
  "SnowballType": "example-value",
  "CreationDate": "example-value",
  "Resources": "example-value",
  "AddressId": "example-value",
  "ShippingOption": "example-value",
  "Notification": "example-value",
  "ForwardingAddressId": "example-value",
  "TaxDocuments": "example-value",
  "OnDeviceServiceConfiguration": "example-value"
}
